version: '3'

networks:
  traefik-net:
    external: true
services:
  frontend:
    build: .
    networks:
      - traefik-net
    restart: always
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.mrfox131.ru`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=le"